-- Добавляем расширенные UTM поля для аналитики рекламы
ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS utm_term VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS utm_content VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS yclid VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS gclid VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS fbclid VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS referrer TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS landing TEXT DEFAULT '';

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS utm_source VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS utm_medium VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS utm_campaign VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS utm_term VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS utm_content VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS yclid VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS gclid VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS fbclid VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS referrer TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS landing TEXT DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_leads_utm_source ON leads(utm_source);
CREATE INDEX IF NOT EXISTS idx_leads_utm_campaign ON leads(utm_campaign);
CREATE INDEX IF NOT EXISTS idx_orders_utm_source ON orders(utm_source);
CREATE INDEX IF NOT EXISTS idx_orders_utm_campaign ON orders(utm_campaign);
