ALTER TABLE users ADD COLUMN IF NOT EXISTS company VARCHAR(255) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(32) DEFAULT 'user';
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan VARCHAR(32) DEFAULT 'free';

UPDATE users SET role = 'admin' WHERE LOWER(email) = 'atyurin2@yandex.ru';
